Weather app
okikiola11/weather-app pull request #1
Opened 2021-03-05 07:53 UTC by okikiola11

I worked on the following:
- Implemented async and await functionality
- Implemented the search functionality for a given city location by a user
- Added the functionality to switch from Celsius to Fahrenheit in degrees

2021-03-05 12:50 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @okikiola11, congratulations on this project :fireworks: The application works as expected. The following requirements have been met:
- User can search for a specific location :100: 
- It has a toggle button to change between Celcius and Fahrenheit :champagne: 
- It changes appearance based on the received data :1st_place_medal: 
- Uses async and await :+1: 
Awesome :smile: 

However, there are a few changes we need to make before proceeding, kindly check the comments below:
- Kindly use ES6 arrow syntax instead of the `function` keyword
- Kindly add `webpack-dev-server` to the package.json file as devDependencies

Once these are resolved, kindly submit another code review request :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-03-05 12:50 UTC, addod19 commented on package.json
> +    "build": "webpack",
Let us kindly fix our `build` script as we did to the `dev` script. Kindly add `--mode production` to the build script as we see in the dev script :muscle:

2021-03-05 12:50 UTC, addod19 commented on package.json
> +    "webpack-cli": "^4.5.0"
Kindly install webpack-dev-server, so we can have it as part of the devDependencies :smile:

2021-03-05 12:50 UTC, addod19 commented on src/index.js
> +async function fetchWeather(city) {
Kindly use ES6 arrow syntax instead of the `function` keyword we have currently :+1:

2021-03-05 12:50 UTC, addod19 commented on src/index.js
> +async function displayWeather(data) {
Kindly use ES6 arrow syntax instead of the `function` keyword we have currently :+1:

2021-03-05 12:50 UTC, addod19 commented on src/index.js
> +async function search() {
Kindly use ES6 arrow syntax instead of the `function` keyword we have currently :+1:

2021-03-05 17:30 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @okikiola11**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] when you display the temperature, the decimal is moved one integer to the right, meaning that instead of 24.567 it's 245.67. please make sure to fix that.



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-03-05 18:13 UTC, okikiola11 commented
@mahmoud717 , please can you explain better, I can't see the error, I also can't find your name on slack

2021-03-05 18:17 UTC, mahmoud717 commented
![Screenshot_2021-03-05-20-16-50-264_com.android.chrome.jpg](https://user-images.githubusercontent.com/60571499/110156530-c030a000-7def-11eb-9823-9f734ae0f698.jpg)

This should be 28 instead of 281

2021-03-05 20:31 UTC, okikiola11 commented
Hi @mahmoud717, can you give me a little more explanation on what to do, because of the ${data. temp} value that I am getting from the API is what I am converting, which is giving me that result. How do I reduce the decimal value??

2021-03-05 20:37 UTC, mahmoud717 commented
Just divide it by ten.
281/10 = 28.1

2021-03-05 21:03 UTC, okikiola11 commented
@mahmoud717 , thank you

2021-03-05 23:55 UTC, ioilmio requested changes
# Hello @okikiola11 👋🏽 
## You implemented all the changes required from previous TSEs, your project is looking, and the code is tidy and easy to understand congrats 🎉 

### There's just one big small problem:
### Your API key is publicly exposed, you have to remove it from your committed code.

### Here's is a [link](https://gist.github.com/derzorngottes/3b57edc1f996dddcab25) to guide you through the process, please read it and follow all the steps needed

*For any doubts please contact me on slack @illuminatosalvatore*

2021-03-06 13:52 UTC, christianotieno approved these changes
### Project Approved 🍾 
Hello @okikiola11 👋🏾 
##
This project has now met all the requirements needed for approval. :clap:
Congratulations on the hard work done with the changes and overall, on this milestone. Good job 👍🏾 
I will go ahead and mark this as complete. Good luck with the next tasks 🥇 
##
### Happy Coding 💻 
#### Christian Otieno (CR)
**| [Twitter](https://twitter.com/iamchrisotieno) | [Github](https://github.com/christianotieno) | [LinkedIn](https://www.linkedin.com/in/christianotieno/) |**

2021-03-06 14:51 UTC, merged